### ISSUE TITLE
Minor Issue: On the FAQ page, text is not contained within the text boxes on mobile safari

### ISSUE THREAD

**Issue by spasion5023** [info442-spr22/d-team#69]
When I clicked on the FAQ page and scrolled down to read the information, the text was overflowing across the page 

Safari on iPhone 13

1. Go to Safari
2. Log on to the live site 
3. Click on the FAQ page 
4. Scroll down through the text 

Expected: text contained in grey boxes

The text runs across the page outside of the gray boxes.
![IMG_1386](https://user-images.githubusercontent.com/85202017/169089261-4f14b5de-79c6-4eee-8e24-68f549ec68aa.jpeg)

**Comment by nihagaddam** [comment]
Gray Boxes are not centered on mobile version of FAQ page.
Environment: Safari, iPhone 13
Expected Result: Centered, Gray boxes.
Actual Result: Gray Boxes are aligned to the left and have big white space on their right.

**Comment by syesil00** [comment]
Similar issue at #68 , will have to add mobile break points to CSS for "FAQ" page.

**Comment by ctang0416** [comment]
Resolved in pull request #105
