### ISSUE TITLE
[Minor Bug] Location Filter Doesn't Change Map Markers

### ISSUE THREAD

**Issue by soshikun** [info442-spr22/d-team#70]
In the "Filter By:" sidebar, the location filters are not affecting the map markers. For example, it is not filtering for specifically Chinatown locations when I click on the Chinatown checkbox. I can still see all of the location markers.

Safari on iPhone XR

Steps to Reproduce:
1. Go to site on Safari
2. Click on the "Chinatown" checkbox on the left sidebar.

Expected Result: Map markers are filtered and I will only see the markers for Chinatown.

Actual Result: All map markers are still visible and it's not clear which one is for Chinatown

**Comment by cherimarie** [comment]
I didn't see this behavior on Chrome on MacOS, so it may be Safari-specific.

**Comment by GuillyGuillaume** [comment]
eventRequirementsArray applicableFilters missmatch

**Comment by GuillyGuillaume** [comment]
[invalid] 
Apply filter button not apparent on mobile interface.

![ecycle](https://user-images.githubusercontent.com/62913726/170890512-315642fb-e52d-457e-be4c-e72b56f1e97d.png)
