### ISSUE TITLE
MINOR BUG: Filter by multiple categories not functioning as expected

### ISSUE THREAD

**Issue by cavazd** [info442-spr22/d-team#71]
**Minor Bug**

* Summary: For the map, filtering by *Location* appears to take priority over filtering by *Days Of Week*. 
* Environment: Firefox 100.0.1 on Windows 11
* Steps to reproduce: Visit Map page. Click on the *Thursday* and *Friday* filters and click filter. Then, click on *Greenwood* filter and new locations appear when I expected more to disappear after getting filtered out. 
* Expected result: I expected when adding a new filter for locations to either stay the same or for some to be removed.
* Actual result: New locations were added

**Comment by GuillyGuillaume** [comment]
[Solved] pull req 
https://github.com/info442-spr22/d-team/pull/96
