### ISSUE TITLE
Major bug: hitting enter on Q&A search leads to Page Not Found

### ISSUE THREAD

**Issue by sharlenef** [info442-spr22/d-team#72]
When using the search bar in the Q&A page, typing up something and hitting enter doesn't lead me to a result. Rather it leads me to 404 Page Not Found, even if I type in something that is listed underneath.

Tested on: Chrome Version 101.0.4951.54 on macOS Big Sur

Steps to reproduce: 

1. Go to FAQ
2. type in "Why recycle electronics?"
3. hit enter

Expected result: leads to "Why recycle electronics?" answer
Actual result: leads to 404 Page Not Found

<img width="431" alt="Screen Shot 2022-05-18 at 9 04 25 AM" src="https://user-images.githubusercontent.com/70997571/169089711-44998dd6-a8c4-45a1-a20e-8ddaa01c5000.png">

**Comment by nihagaddam** [comment]
Additional Info: Unable to go back to the FAQ search after using the search bar.
Expected Result: Able to press back button and redirect to previous page after receiving error for searching for a FAQ link.
Actual Result: Back Button is nonfunctional and does not allow user to go to previous page.

Environment: Macbook Air, Chrome

**Comment by syesil00** [comment]
Fixing the firebase routing in PR #99 resolved this issue.
