### ISSUE TITLE
Navbar fixed on page as scrolling down. The nav bar show up behind the boxes as you scroll down on the webpage. (Bug) (Minor)))

### ISSUE THREAD

**Issue by avaghela-1925502** [info442-spr22/d-team#74]
general summary of the problem: The navbar is still on the screen and for some reason it is behind the other text boxes while I scroll down the web page making it distracting. Can still hover over and click on it on accident.

environment it was encountered in: Chrome on MacOs

steps to reproduce: Add media query to have nav bar stay at the top

expected result: Scrollable page with navbar at top

actual result: Navbar following my scroll and accidentally clicking on it since it is in the way

**Comment by GuillyGuillaume** [comment]
WZ - Work worth doing, will be completed in the next sprint
check CSS
