### ISSUE TITLE
Refreshing page leads to a 404 Page not found error (Minor) (Bug)

### ISSUE THREAD

**Issue by avaghela-1925502** [info442-spr22/d-team#75]
general summary of the problem: refreshing page leads to a 404 Page not found error on mobile device and mac
environment it was encountered in: Chrome on MacOs
steps to reproduce: Check why refreshing causes this and have it navigate to home page
expected result: Taken back to current or home page
actual result: 404 page not found error

**Comment by syesil00** [comment]
Seems to be the same issue as https://dev.to/rajeshroyal/page-not-found-error-on-netlify-reactjs-react-router-solved-43oa (should be marked minor for grading purposes).

**Comment by syesil00** [comment]
resolved in pull request #99
