### ISSUE TITLE
(Major) Navigating to an FAQ link and going back causes site to give 404 page not found error

### ISSUE THREAD

**Issue by cmarq07** [info442-spr22/d-team#76]

**Comment by cmarq07** [comment]
Encountered on Chrome on Mac
Go to FAQ page, click a link that redirects you within the same tab (doesn't open a new one) and go back to the original page to produce this error

**Comment by syesil00** [comment]
Duplicate solution as https://github.com/info442-spr22/d-team/issues/75. However, for grading purposes, I believe this is not a duplicate issue and the reporter should still receive credit.
