### ISSUE TITLE
Minor Bug: Unable to unselect availability once selected

### ISSUE THREAD

**Issue by abequette99** [info442-spr22/d-team#77]
Summary: When working with the filters I wanted to unselect the availability however I was unable to, one of them had to be selected at all times unless you went to another page and came back.

Environment: Chrome Version 101.0.4951.67 

Steps: 
1. Click on one of the availability filters of all locations or currently open. 
2. Try to unselect it. Will not unselect

Expected results: I expected to have non of the two field filled

Actual results: one of the fields in the availability filter was selected at all times once selected

**Comment by GuillyGuillaume** [comment]
Work not worth doing
having "All Locations" is the same as having nothing selected.
