### ISSUE TITLE
Enhancement: Make Nav bar not go behind columns when scrolling

### ISSUE THREAD

**Issue by abequette99** [info442-spr22/d-team#78]
Description: When scrolling the nav bar goes behind the three columns, it would be useful to have a planted nav bar that does not move when scrolling.

Explanation: It is helpful to have a navbar that does not move especially when scrolling because it allows users to move around to different pages no matter how far down they are on a page. By having the nav bar available at all time no matter where you are on the page it will be easier to access all the pages without scrolling to the top to get back to them.

**Comment by aidanthorns** [comment]
Duplicate #74

**Comment by GuillyGuillaume** [comment]
[Solved}

https://github.com/info442-spr22/d-team/pull/98
