### ISSUE TITLE
(Minor) Selecting more than one days of week filter does not filter as intended.

### ISSUE THREAD

**Issue by soopark82** [info442-spr22/d-team#79]
![image](https://user-images.githubusercontent.com/63069316/169095650-798e678e-bfd0-4688-a0ae-3f3da3085ada.png)

Once I got "No Location Found" message, the filter stopped working (even having checked all the checkboxes which should retrieve all results).

Severity: minor
Environment: Chrome v101.0.4951.67 on Windows
expected result: clicking the "search" button retrieving results based on filters even after "No Location Found" alert message
actual result: clicking the "search" button doesn't do anything after

**Comment by GuillyGuillaume** [comment]
Work worth doing, will be completed in the next sprint
eventRequirementsArray applicableFilters missmatch

**Comment by GuillyGuillaume** [comment]
[Solved] pull req 
https://github.com/info442-spr22/d-team/pull/96
