### ISSUE TITLE
Add navigation to your title in nav bar *Enhancement*

### ISSUE THREAD

**Issue by epdooley** [info442-spr22/d-team#83]
I think it would be helpful to have your title of your site on the left of the nav bar reroute back to the initial map page that you first land on when entering the site. I think of that page as the home page since that is what I first encountered, so when I was on different pages, my first instinct was to click the title to get back there rather than the 'Map' button in the nav bar.

**Comment by aidanthorns** [comment]
Already have the option to go back to whatever page the user requests in the navigation bar.

**Comment by syesil00** [comment]
Resolved in PR #104
