### ISSUE TITLE
Bug: Information Cards on Home page are too squished on mobile to be functional (Minor)

### ISSUE THREAD

**Issue by pranavshekar** [info442-spr22/d-team#84]
On Safari on an iPhone XR, as shown in the picture, the Filter and Map are really squished. The reality is they're squished when they should probably be stacked. This makes it nearly impossible to use the Map function and Zoom in and see what information markers are nearby.

![IMG_AA78C230D920-1](https://user-images.githubusercontent.com/62967217/169097803-acb280fe-ec03-44ea-9ccb-6844092612aa.jpeg)

**Comment by syesil00** [comment]
Add mobile CSS breakpoints for elements on the map page.

**Comment by syesil00** [comment]
Resolved in pull request #97
