### ISSUE TITLE
(Minor bug) When dragging the map, the cursor changes when it exits the map

### ISSUE THREAD

**Issue by fretws** [info442-spr22/d-team#87]
Steps to recreate: Navigate to home page, click and drag map until cursor leaves the bounds of the map element
Expected result: The cursor stays as the grasping hand icon until I release the mouse button
Actual result: The cursor changes based on what the cursor is currently hovering over on the page
Windows 10, Chrome

**Comment by GuillyGuillaume** [comment]
Work not worth doing
Visual appearance and leaflet related bug.
Don't know how to fix.
