### ISSUE TITLE
[Enhancement] Add a search button in FAQ page

### ISSUE THREAD

**Issue by MARY4177** [info442-spr22/d-team#89]
Right now your FAQ page does have a search bar but not a search button next to it.
Some users might wonder where to click on after typing in the search bar, so it would be better to include it just in case.
Otherwise, consider including a search icon within the box to indicate to users that they can just press enter button.
![image](https://user-images.githubusercontent.com/55933930/169103420-be5c62f2-069b-4dff-b94d-f52b37b126d1.png)
![image](https://user-images.githubusercontent.com/55933930/169103499-e9647200-da05-4ea5-8041-6bca6099d7b3.png)

**Comment by ctang0416** [comment]
Improve UX by adding a search button or icon

**Comment by syesil00** [comment]
Resolved in PR #103
