### ISSUE TITLE
Enhancement: Include an About Page or overall landing page and the authors of the website

### ISSUE THREAD

**Issue by hannanajmal** [info442-spr22/d-team#90]
Maybe including a page on your website that describes the purpose of the website, its instead purpose and who helped develop it could give more context about the intent of your web application. You could also include the Authors of the website in the footer instead of making a whole separate page for it. It's just a good way to see who was involved in the apps creation in the chance someone would like to contact one of the team members.

**Comment by aidanthorns** [comment]
Duplicate #88
